default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

staging:
  adapter: postgresql
  encoding: unicode
  database: kanban_staging

test:
  <<: *default
  database: db/test.sqlite3
