source 'https://rubygems.org'

gem 'rails', '4.2.0'
ruby '2.2.0'

gem 'active_model_serializers', '~> 0.8.0'
gem 'acts_as_list'
gem 'bcrypt-ruby', '~> 3.1.0'
gem 'thin'

group :development, :test do
  gem 'annotate'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'letter_opener'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'rspec-rails'
  gem 'shoulda-matchers', '~> 2.8.0'
  gem 'sqlite3'
end

group :production, :staging do
  gem 'pg'
end
